apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: grafana
spec:
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - image: mireg.wr25.org/grafana:latest@sha256:5306338233ddb5a82ef079d8a795f58e668a0fc60975ce1d7886eb7642edc838
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/grafana/grafana/data
          name: grafanadata
      restartPolicy: Always
      volumes:
      - name: grafanadata
        persistentVolumeClaim:
          claimName: grafanadata
