apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: grafana
spec:
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - image: mireg.wr25.org/grafana:latest@sha256:d48bc7a6e5449f3d59768c4d1e858a81800b2f745a0acdea2cf3b2ab799590d0
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/grafana/grafana/data
          name: grafanadata
      restartPolicy: Always
      volumes:
      - name: grafanadata
        persistentVolumeClaim:
          claimName: grafanadata
