apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: grafana
spec:
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - image: mireg.wr25.org/grafana:latest@sha256:60b5de761091a5e7bbae6ec5c304d8c24edfb1f3b4e57708be092ca3ba53ff1b
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/grafana/grafana/data
          name: grafanadata
      restartPolicy: Always
      volumes:
      - name: grafanadata
        persistentVolumeClaim:
          claimName: grafanadata
